# Generated by Django 6.1.1 on 2026-09-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings')], default='checking', max_length=16)),
                ('pin_hash', models.CharField(max_length=256)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=16)),
                ('failed_pin_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(help_text='E.164, e.g. +41791234567', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id_last4', models.CharField(blank=True, max_length=4)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('level', models.CharField(choices=[('basic', 'Basic (account + PIN)'), ('elevated', 'Elevated (PIN + OTP)')], default='basic', max_length=16)),
                ('caller_id', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(default='voice', max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to='bank.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(default='Visa', max_length=20)),
                ('card_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=16)),
                ('last4', models.CharField(max_length=4)),
                ('expiry_month', models.PositiveSmallIntegerField(default=12)),
                ('expiry_year', models.PositiveSmallIntegerField(default=2030)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=16)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank.account')),
            ],
            options={
                'ordering': ['account__account_number', 'last4'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank.customer'),
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=256)),
                ('purpose', models.CharField(default='card_block', max_length=32)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('channel', models.CharField(default='sms', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='bank.authsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('category', models.CharField(default='card_block', max_length=32)),
                ('reason', models.CharField(choices=[('lost', 'Lost'), ('stolen', 'Stolen'), ('compromised', 'Compromised / fraud suspected'), ('damaged', 'Damaged'), ('other', 'Other')], default='other', max_length=32)),
                ('incident_description', models.TextField(blank=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('failed', 'Failed')], default='open', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bank.account')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bank.card')),
                ('opened_via_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='bank.authsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=16)),
                ('destination', models.CharField(max_length=120)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('provider', models.CharField(default='console', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bank.account')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bank.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(db_index=True, max_length=64)),
                ('ok', models.BooleanField(default=False)),
                ('http_status', models.PositiveSmallIntegerField(default=200)),
                ('error_code', models.CharField(blank=True, max_length=48)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('session_token_prefix', models.CharField(blank=True, max_length=12)),
                ('remote_addr', models.CharField(blank=True, max_length=64)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='bank.account')),
            ],
            options={
                'verbose_name': 'tool call log',
                'verbose_name_plural': 'tool call logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('account', 'last4'), name='unique_last4_per_account'),
        ),
    ]
