# Generated by Django 6.1.1 on 2026-09-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('email_provider', models.CharField(choices=[('console', 'Console (stored, not sent)'), ('smtp', 'SMTP'), ('brevo', 'Brevo (API)')], default='console', max_length=16)),
                ('sms_provider', models.CharField(choices=[('console', 'Console (stored, not sent)'), ('brevo', 'Brevo (API)'), ('twilio', 'Twilio')], default='console', max_length=16)),
                ('default_channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=16)),
                ('brevo_api_key', models.CharField(blank=True, max_length=256)),
                ('brevo_sender_email', models.EmailField(blank=True, max_length=254)),
                ('brevo_sender_name', models.CharField(blank=True, default='AIDA Bank', max_length=80)),
                ('brevo_sms_sender', models.CharField(blank=True, default='AIDABank', help_text='Alphanumeric sender shown on the SMS. Max 11 characters.', max_length=11)),
                ('smtp_host', models.CharField(blank=True, max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=200)),
                ('smtp_password', models.CharField(blank=True, max_length=256)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, max_length=254)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=64)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=128)),
                ('twilio_from_number', models.CharField(blank=True, max_length=32)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'provider settings',
                'verbose_name_plural': 'provider settings',
            },
        ),
    ]
