# Generated by Django 6.1.1 on 2026-09-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_providersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TunnelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('mode', models.CharField(choices=[('auto', 'Auto-detect from the ngrok agent'), ('manual', 'Manual URL'), ('off', 'Off (use PUBLIC_BASE_URL from the environment)')], default='auto', max_length=16)),
                ('agent_api_url', models.CharField(blank=True, help_text='ngrok agent API. http://ngrok:4040/api/tunnels inside compose.', max_length=200)),
                ('manual_url', models.URLField(blank=True, help_text='Used when mode is Manual. E.g. a cloudflared URL or a deployed host.')),
                ('detected_url', models.URLField(blank=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tunnel settings',
                'verbose_name_plural': 'tunnel settings',
            },
        ),
    ]
