# Generated by Django 6.1.1 on 2026-09-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_tunnelsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnelsettings',
            name='ngrok_authtoken',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
