# Generated by Django 6.1.1 on 2026-09-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_tunnelsettings_ngrok_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('require_otp_for_card_block', models.BooleanField(default=False, help_text='Require a one-time code before a card can be blocked.')),
                ('updated_by', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'security settings',
                'verbose_name_plural': 'security settings',
            },
        ),
    ]
